services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Plenta\ContaoGithubReleases\:
        resource: ../src/*
        exclude: ../src/{Entity,Migrations,Resources,Tests}
